a = {'members': 26, 'coverage': 0, 'total_price': 850000, 'channels': [
    {'id': 31, 'client_id': 3, 'type': {'id': 1, 'type': 'telegram'}, 'url': 'https://t.me/uz_news',
     'name': '🌐UzNews🌐', 'category': 'Развлечения и Юмор',
     'description': 'Новостной канал оповещающий интересные событии в Узбекистане',
     'sex_ratio': {'id': 3, 'ratio': '🙋\u200d♂️50% / 50%🙋\u200d♀️'}, 'text_limit': 500, 'views': 0, 'subscribers': 22,
     'status': 'active', 'area_language': [{'id': 3, 'language': '🇷🇺 Русский'}],
     'area_region': [{'id': 1, 'region': 'Андижан'}, {'id': 2, 'region': 'Бухара'}, {'id': 3, 'region': 'Джизак'},
                     {'id': 4, 'region': 'Кашкадарья'}, {'id': 5, 'region': 'Навои'}, {'id': 6, 'region': 'Наманган'},
                     {'id': 7, 'region': 'Самарканд'}, {'id': 8, 'region': 'Сурхандарья'},
                     {'id': 9, 'region': 'Сырдарья'}, {'id': 10, 'region': 'Ташкент'}, {'id': 11, 'region': 'Фергана'},
                     {'id': 12, 'region': 'Хорезм'}, {'id': 13, 'region': 'Таш. Область'},
                     {'id': 14, 'region': 'Каракалпакстан'}],
     'area_age': [{'id': 2, 'age': '18-34 лет'}, {'id': 3, 'age': '35-44 лет'}, {'id': 4, 'age': '45-54 лет'}],
     'area_accommodation': [{'id': 11, 'accommodation': 'без топа 24 часа в ленте', 'price': 500000, 'view': 0}],
     'current_accommodation': [11]}, {'id': 172, 'client_id': 3, 'type': {'id': 1, 'type': 'telegram'},
                                      'url': 'https://t.me/Qashqadaryo_Qarshili_Shahrisabz',
                                      'name': 'Qashqadaryo e;lonlari', 'category': 'Региональные',
                                      'description': 'Развлекательный канал с фото и видео материалами',
                                      'sex_ratio': {'id': 2, 'ratio': '🙋\u200d♂️75% / 25%🙋\u200d♀️'}, 'text_limit': 500,
                                      'views': 0, 'subscribers': 4, 'status': 'active',
                                      'area_language': [{'id': 1, 'language': '🇺🇿 Узбекский'}],
                                      'area_region': [{'id': 4, 'region': 'Кашкадарья'}],
                                      'area_age': [{'id': 1, 'age': 'до 18 лет'}, {'id': 2, 'age': '18-34 лет'},
                                                   {'id': 3, 'age': '35-44 лет'}, {'id': 4, 'age': '45-54 лет'},
                                                   {'id': 5, 'age': '54 и старше'}], 'area_accommodation': [
            {'id': 11, 'accommodation': 'без топа 24 часа в ленте', 'price': 350000, 'view': 0}],
                                      'current_accommodation': [11]}]}
